config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root to: 'users/homepage#index'

  devise_for :users, path: "user", controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
  }

  namespace :users, path: 'user' do
    get '/homepage', to: 'homepage#index', as: 'homepage'
    get '/do', to: 'quizzes#do_quiz', as: 'do_quiz'
    post '/do', to: 'quizzes#do_quiz_submit', as: 'do_quiz_submit'
    get '/history', to: 'quizzes#history', as: 'history'

    get '/profile', to: 'homepage#profile', as: 'profile'
    patch '/profile/update', to: 'homepage#update', as: 'update_profile'
    patch '/profile/password', to: 'homepage#change_password', as: 'change_password'

    resources :quizzes do
      post '/start', to: 'quizzes#start', as: 'start'

      get '/do/classic', to: 'quizzes#classic', as: 'classic'
      post '/do/classic', to: 'quizzes#submit_classic', as: 'submit_classic'
      get '/do/live', to: 'quizzes#live', as: 'live'
      post '/do/live', to: 'quizzes#submit_live', as: 'submit_live'

      get '/answers', to: 'quizzes#answers', as: 'answers'
      get '/answers/:id/mark', to: 'quizzes#mark', as: 'mark'
      post '/answers/:id/mark', to: 'quizzes#submit_mark', as: 'submit_mark'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :quizzes
  has_many :quiz_answers
end

app/controllers/users/base_controller.rb
class Users::BaseController < ActionController::Base
  breadcrumb 'Home', :root_path
  before_action :authenticate_user!
  before_action :get_user
  before_action :get_uri

  layout 'dashboard'

  private

  def get_user
    @user = current_user
  end

  def get_uri
    @base_url = URI(request.fullpath).path.split('/').last
  end
end

app/controllers/users/homepage_controller.rb
class Users::HomepageController < Users::BaseController
  def index

  end

  def profile

  end

  def update
    @update = @user.update!(profile_params)
    redirect_to root_path if @update
  end

  def change_password
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    
    @update = @user.update!(password_params)
    redirect_to request.referrer if @update
  end

  private

  def profile_params
    params.require(:user).permit(:name, :email)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/users/quizzes_controller.rb
class Users::QuizzesController < Users::BaseController
  

  def index
    @quizzes = @user.quizzes.order(start_date: :desc, end_date: :asc)
  end

  def new
    @quiz = Quiz.new
  end

  def create
    quiz = Quiz.create(quiz_params.merge(user: @user, code: rand(10000000...99999999)))

    count = params['questions']['number'].to_i - 1
    
    for i in 0..count do
      data = params['questions']['data'][i.to_s].split(',')
      if data[2] != 'deleted'
        Question.create(quiz: quiz, q_text: data[0], q_type: data[2], marks: data[1], answer_1: data[3], answer_2: data[4], answer_3: data[5], answer_4: data[6], correct_answer: data[7])
      end
    end
    
    redirect_to users_quizzes_path
  end

  def edit
    @quiz = Quiz.find(params[:id])
    @questions = @quiz.questions
    
    @q_array = []
    @questions.each do |q|
      @q_array << [q.q_text, q.marks, q.q_type, q.answer_1, q.answer_2, q.answer_3, q.answer_4, q.correct_answer]
    end
  end

  def update
    quiz = Quiz.find(params[:id])
    quiz.update(quiz_params)

    quiz.questions.destroy_all
    
    count = params['questions']['number'].to_i - 1
    
    for i in 0..count do
      data = params['questions']['data'][i.to_s].split(',')
      if data[2] != 'deleted'
        Question.create(quiz: quiz, q_text: data[0], q_type: data[2], marks: data[1], answer_1: data[3], answer_2: data[4], answer_3: data[5], answer_4: data[6], correct_answer: data[7])
      end
    end
    
    redirect_to users_quizzes_path
  end

  def destroy
    quiz = Quiz.find(params[:id])
    
    quiz.questions.each do |q|
      q.question_answers.destroy_all
    end
    quiz.questions.destroy_all

    quiz.update(user: nil)
    quiz.destroy
  end

  def do_quiz
    
  end

  def do_quiz_submit
    quiz = Quiz.find_by(code: params[:code].to_i)

    if !quiz.nil?
      if DateTime.now >= DateTime.new(quiz.start_date.year, quiz.start_date.month, quiz.start_date.day, quiz.start_time.hour, quiz.start_time.min, quiz.start_time.sec, quiz.start_time.zone)
        if DateTime.now <= DateTime.new(quiz.end_date.year, quiz.end_date.month, quiz.end_date.day, quiz.end_time.hour, quiz.end_time.min, quiz.end_time.sec, quiz.end_time.zone)
          if quiz.q_type == 'classic'
            render :json => {id: quiz.id, type: 'classic'}
          else
            render :json => {id: quiz.id, type: 'live'}
          end
        else
          render :json => {id: 0, type: 'fail'}
        end
      else
        render :json => {id: 0, type: 'fail'}
      end
    else
      render :json => {id: 0, type: 'fail'}
    end
  end

  def history
    @history = @user.quiz_answers
  end

  def start

  end

  def classic
    @quiz = Quiz.find(params[:quiz_id])
    @answer = QuizAnswer.new

    @end_time = DateTime.new(@quiz.end_date.year, @quiz.end_date.month, @quiz.end_date.day, @quiz.start_time.hour, @quiz.start_time.min, @quiz.start_time.sec, @quiz.start_time.zone).strftime("%b %-d, %Y %H:%M:%S")
  end

  def submit_classic
    quiz = Quiz.find(params[:quiz_id])
    qa = QuizAnswer.create(quiz: quiz, user: @user, start_date: quiz.start_date, end_date: quiz.end_date, start_time: quiz.start_time, end_time: quiz.end_time)
    
    params['answers'].each do |a|
      QuestionAnswer.create(question_id: a[0], quiz_answer: qa, marks: nil, answer: a[1])
    end
    
    redirect_to root_path
  end

  def live
    @quiz = Quiz.find(params[:quiz_id])
    @host = false
    
    if @quiz.user != @user
      @qa = QuizAnswer.where(user: @user).where(quiz: @quiz).first
      if @qa.nil?
        @qa = QuizAnswer.create(quiz: @quiz, user: @user, start_date: @quiz.start_date, end_date: @quiz.end_date, start_time: @quiz.start_time, end_time: @quiz.end_time)
      end
    else
      @host = true;
    end
  end

  def submit_live
  end

  def answers
    @quiz = Quiz.find(params[:quiz_id])
  end

  def mark
    @quiz = Quiz.find(params[:quiz_id])
    @qa = QuizAnswer.find(params[:id])
  end

  def submit_mark
    total = 0
    params['marks'].each do |m|
      QuestionAnswer.find(m[0].to_i).update(marks: m[1].to_i)
      total += m[1].to_i
    end

    QuizAnswer.find(params[:id]).update(total_marks: total)
    
    redirect_to users_quiz_answers_path(params[:quiz_id])
  end

  private

  def quiz_params
    params.require(:quiz).permit(:name, :q_type, :description, :start_date, :end_date, :start_time, :end_time)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
    flash[:warning] = 'You has been signed out.'
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/views/users/quizzes/_live_end.html.erb
<div id="live-body" class="page-content">
  <h1 class="mb-2"><%= name %></h1>
  <hr class="pb-2 my-4">

  <div class="card-deck row">
    <div class="col-lg-2"></div>
    <div class="col-12 col-lg-8">
      <div class="info-box card mb-30">
        <div class="card-body">
          <div id="end-top" class="form-row">
            <div class="col-12">
              <div class="form-group">
                <label style="font-size: 1.5em; color:black">Quiz Ended</label>
              </div>
            </div>
          </div>
          <div class="card h-100">
            <div class="card-body">
              <h3 class="card-label-md text-nowrap mb-3 flex-fill">Final Scores</h5>
              <div id="end-list" class="attendance-list" style="height: 300px; overflow-y: scroll; border: 1px solid #ccd0e4; border-radius: 0 0 3px 3px; padding: 1rem;">
                <% scores.each_with_index do |s, i| %>
                  <div class="row">
                    <div class="col-4">
                      <h5 class="mb-2"><%= (i + 1).to_s %>.</p>
                    </div>
                    <div class="col-4">
                      <h5 class="mb-2"><%= s[0] %></p>
                    </div>
                    <div class="col-4">
                      <h5 class="mb-2"><%= s[1] %></p>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="btn-group info-box-action d-flex" role="group">
            <button id="exit-button" class="info-box-btn-main flex-fill btn btn-blue-gradient" style="font-size: 1.3em; text-align: center; padding: 1rem !important;">Exit</button>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-2"></div>
  </div>
</div>

app/views/users/quizzes/_live_leaderboard.html.erb
<div id="live-body" class="page-content">
  <h1 class="mb-2"><%= name %></h1>
  <hr class="pb-2 my-4">

  <div class="card-deck row">
    <div class="col-lg-2"></div>
    <div class="col-12 col-lg-8">
      <div class="info-box card mb-30">
        <div id="lb-body" class="card-body">
          <div class="form-row">
            <div class="col-12">
              <div class="form-group">
                <label style="font-size: 1.5em; color:black">Question <%= number %></label>
              </div>
            </div>
            <div class="col-12 mt-3">
              <h4>Correct Answer: <%= correct_answer %></h4>
              <h4>Marks Awarded: <%= marks %></h4>
            </div>
          </div>
          <div class="card h-100">
            <div class="card-body">
              <h3 class="card-label-md text-nowrap mb-3 flex-fill">Score Leaderboard</h5>
              <div id="registered-list" class="attendance-list" style="height: 300px; overflow-y: scroll; border: 1px solid #ccd0e4; border-radius: 0 0 3px 3px; padding: 1rem;">
                <% scores.each_with_index do |s, i| %>
                  <div class="row">
                    <div class="col-4">
                      <h5 class="mb-2"><%= (i + 1).to_s %>.</p>
                    </div>
                    <div class="col-4">
                      <h5 class="mb-2"><%= s[0] %></p>
                    </div>
                    <div class="col-4">
                      <h5 class="mb-2"><%= s[1] %></p>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-2"></div>
  </div>
</div>

app/views/users/quizzes/answers.html.erb
<!-- Page Content -->
<div class="page-content">
  <div class="page-header d-flex flex-column flex-md-row align-items-md-center">
      <div class="page-header-left flex-fill">
          <div class="page-header-title d-flex">
              <div class="page-info mt-3 ml-0">
                <h5 class="page-title">Answer List</h5>
              </div>
          </div>
      </div>
  </div>


  <!-- Section Header -->
  <div class="section-header d-md-flex align-items-center">
    <div class="section-header-left flex-fill">
      <a href="<%= users_quizzes_path %>" class="page-btn-link">
        <i class="icon icon-reply"></i>
        Back to Quiz List
      </a>
    </div>
  </div>
  <!-- / Section Header -->

  <div class="table-wrapper table-responsive">
    <table id="contact-groups" class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Marks</th>
          <% if @quiz.q_type == 'classic' %>
            <th scope="col">Action</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @quiz.quiz_answers.each do |qa| %>
          <tr>
            <td scope="col"><%= qa.user.name %></td>
            <% if qa.total_marks.nil? %>
              <td scope="col">Pending</td>
            <% else %>
              <td scope="col"><%= qa.total_marks %></td>
            <% end %>
            <% if @quiz.q_type == 'classic' %>
              <td class="table-action">
                <%= link_to 'Mark', users_quiz_mark_path(@quiz.id, qa.id), class: 'btn btn-info', data: { turbolinks: false } %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/users/quizzes/classic.html.erb
<div class="page-content">
  <%= form_for(@answer, url: users_quiz_submit_classic_path, method: :post) do |f| %>
    <div class="page-header d-flex flex-column flex-md-row align-items-md-center">
      <div class="page-header-left flex-fill">
        <div class="page-header-title d-flex">
          <div class="page-info mt-3 ml-0">
            <h5 class="page-title"><%= @quiz.name %></h5>
          </div>
        </div>
      </div>
    </div>
    <div class="section-header d-md-flex align-items-center">
      <div class="section-header-left">
        <h5 id="timer" class="px-3 py-2" style="background-color: white;">Loading...</h5>
      </div>
      <div class="section-header-right ml-auto">
        <button type="submit" class="btn btn-primary text-uppercase">Submit</button>
      </div>
    </div>
    <div class="card mt-3 mt-md-4">
      <div class="card-header">
        <h5 class="card-title">Answers</h5>
      </div>
      <div class="card-body">
        <% @quiz.questions.each_with_index do |q, i| %>
          <% if q.q_type == 'written' %>
            <div class="form-row">
              <div class="col-12">
                <div class="form-group">
                  <label style="font-size: 15px;">Question <%= i + 1 %> (<%= q.q_type.capitalize %>)</label>
                  <textarea class="form-control form-readonly" rows="4" style="resize: none;" readonly><%= q.q_text %></textarea>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group">
                  <label>Answer:</label>
                  
                  <textarea required class="form-control" name="answers[<%= q.id %>]" id="answer" rows="4" style="resize: none;"></textarea>
                </div>
              </div>
            </div>
            <hr class="pb-2 mt-1 mt-md-2 mb-3 mb-md-4">
          <% else %>
          <div class="form-row">
              <div class="col-12">
                <div class="form-group">
                  <label style="font-size: 15px;">Question <%= i + 1 %> (<%= q.q_type.capitalize %>)</label>
                  <textarea class="form-control form-readonly" rows="4" style="resize: none;" readonly><%= q.q_text %>
                  </textarea>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group">
                  <label>Answer Choices</label>
                  <textarea class="form-control form-readonly" rows="4" style="resize: none;" readonly>
A. <%= q.answer_1 %>
B. <%= q.answer_2 %>
C. <%= q.answer_3 %>
D. <%= q.answer_4 %>
                  </textarea>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="form-group">
                  <label>Answer:</label>
                  <select required="required" class="form-control" name="answers[<%= qqa.id %>]" id="answer">
                    <option value=""></option>
                    <option value="1">Answer A</option>
                    <option value="2">Answer B</option>
                    <option value="3">Answer C</option>
                    <option value="4">Answer D</option>
                  </select>
                </div>
              </div>
            </div>
            <hr class="pb-2 mt-1 mt-md-2 mb-3 mb-md-4">
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="section-header d-md-flex align-items-center">
      <div class="section-header-right ml-auto mt-3 mt-md-4">
        <button type="submit" class="btn btn-primary text-uppercase">Submit</button>
      </div>
    </div>
  <% end %>
</div>

<script>
  var end_time = new Date("<%= @end_time %>").getTime();

  var timer = setInterval(function() {
    var now = new Date().getTime();

    var distance = end_time - now;

    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);

    document.getElementById("timer").innerHTML = days + "d " + hours + "h " + minutes + "m " + seconds + "s ";

    if (distance < 0) {
      clearInterval(timer);
      document.getElementById("timer").innerHTML = "ENDED";

      window.location.replace('/user/do');
    }
  }, 1000);
</script>

app/views/users/quizzes/index.html.erb
<!-- Page Content -->
<div class="page-content">
  <div class="page-header d-flex flex-column flex-md-row align-items-md-center">
      <div class="page-header-left flex-fill">
          <div class="page-header-title d-flex">
              <div class="page-info mt-3 ml-0">
                <h5 class="page-title">My Quizzes</h5>
              </div>
          </div>
      </div>
  </div>


  <!-- Section Header -->
  <div class="section-header d-md-flex align-items-center">
    <div class="section-header-left flex-fill">
      <h4 class="section-title">Quiz List</h4>
    </div>
    <div class="section-header-right ml-auto">
      <button class="btn btn-danger" id="bulkDelete">Bulk Delete</button>
      <div class="btn-group" role="group">
        <%= link_to 'Create New Quiz', new_users_quiz_path, class: 'btn btn-primary-gradient' %>
      </div>
    </div>
  </div>
  <!-- / Section Header -->

  <!-- Quiz List Table -->
  <div class='alert alert-success' id="bulk-notification">Successfully deleted selected Quizzes.</div>
  <div class="table-wrapper table-responsive">
    <table id="contact-groups" class="table table-striped">
      <thead>
        <tr>
          <th scope="col">
            <div class="form-check">
              <input type="checkbox" class="custom-check-input checkAll" />
            </div>
          </th>
          <th scope="col">Quiz</th>
          <th scope="col">Type</th>
          <th scope="col">Start Time</th>
          <th scope="col">End Time</th>
          <th scope="col">Code</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @quizzes.each do |q|%>
          <tr id="row_<%= q.id %>">
            <td scope="col">
              <div class="form-check">
                <input type="checkbox" class="custom-check-input check" value="<%= q.id %>" />
              </div>
            </td>
            <td scope="col"><%= q.name %></td>
            <td scope="col"><%= q.q_type.capitalize %></td>
            <td scope="col"><%= DateTime.new(q.start_date.year, q.start_date.month, q.start_date.day, q.start_time.hour, q.start_time.min, q.start_time.sec, q.start_time.zone).strftime("%Y-%-m-%-d %H:%M:%S") %></td>
            <td scope="col"><%= DateTime.new(q.end_date.year, q.end_date.month, q.end_date.day, q.start_time.hour, q.start_time.min, q.start_time.sec, q.start_time.zone).strftime("%Y-%-m-%-d %H:%M:%S") %></td>
            <td scope="col"><%= q.code %></td>
            <td class="table-action">
              <%= link_to 'Edit', edit_users_quiz_path(q.id), class: 'btn btn-success', data: { turbolinks: false } %>
              <%= link_to 'Delete', users_quiz_path(q.id), id: q.id, class: 'btn btn-danger btn-delete', data: {confirm: 'Are you sure want to delete this quiz?'}, method: :delete %>
              <%= link_to 'Answers', users_quiz_answers_path(q.id), class: 'btn btn-info', data: { turbolinks: false } %>
              <% if q.q_type == 'live' %>
                <%= link_to 'Start', users_quiz_live_path(q.id), class: 'btn btn-info', data: { turbolinks: false } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <!-- / Quiz List Table -->

</div>



<!-- / Page Content -->
<script>
  $('#bulk-notification').hide();
  
  $('#bulkDelete').on('click', function(e){
    var arr = [];

    $(".check:checked").each(function() {
      arr.push($(this).val());
    });
    
    arr.forEach(function(item) {
        $.ajax({
          url: '/user/quizzes/' + item,
          type: 'DELETE',
          data: {id: item},
          success: function(result) {
            $('#row_' + item).remove();
          }
        });
    });

    $('#bulk-notification').show();

    setTimeout(function() {
      window.location.reload();
    }, 5000);
  });

  $('.btn-delete').click(function(e) {
    $('#row_' + $(this).attr('id')).remove();
  });
</script>

app/views/users/quizzes/mark.html.erb
<!-- Page Content -->
<div class="page-content">
  <%= form_for(@qa, url: users_quiz_submit_mark_path, method: :post) do |f| %>
    <div class="page-header d-flex flex-column flex-md-row align-items-md-center">
      <div class="page-header-left flex-fill">
        <div class="page-header-title d-flex">
          <div class="page-info mt-3 ml-0">
            <h5 class="page-title">Mark Jonathan Yap's Answers</h5>
          </div>
        </div>
      </div>
    </div>
    <div class="section-header d-md-flex align-items-center">
      <div class="section-header-left flex-fill">
        <a href="<%= users_quiz_answers_path %>" class="page-btn-link">
          <i class="icon icon-reply"></i>
          Back to Answer List
        </a>
      </div>
      <div class="section-header-right ml-auto">
        <button type="submit" class="btn btn-primary text-uppercase">Submit</button>
      </div>
    </div>
    <div class="card mt-3 mt-md-4">
      <div class="card-header">
        <h5 class="card-title">Answers</h5>
      </div>
      <div class="card-body">
        <% @quiz.questions.each_with_index do |q, i| %>
          <% qqa = q.question_answers.find_by(quiz_answer: @qa) %>
          <% if q.q_type == 'written' %>
            <div class="form-row">
              <div class="col-12">
                <div class="form-group">
                  <label style="font-size: 15px;">Question <%= i + 1 %> (<%= q.q_type.capitalize %>)</label>
                  <textarea class="form-control form-readonly" rows="4" style="resize: none;" readonly><%= q.q_text %>
                  </textarea>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group">
                  <label>Answer</label>
                  <textarea class="form-control form-readonly" rows="4" style="resize: none;" readonly><%= qqa.answer %></textarea>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="form-group">
                  <label>Marks to Award (Max <%= q.marks %>)</label>
                  <input required="required" class="form-control" type="number" name="marks[<%= qqa.id %>]" id="mark" min="0" max="<%= q.marks %>">
                </div>
              </div>
            </div>
            <hr class="pb-2 mt-1 mt-md-2 mb-3 mb-md-4">
          <% else %>
            <div class="form-row">
              <div class="col-12">
                <div class="form-group">
                  <label style="font-size: 15px;">Question <%= i + 1 %> (<%= q.q_type.capitalize %>)</label>
                  <textarea class="form-control form-readonly" rows="4" style="resize: none;" readonly><%= q.q_text %>
                  </textarea>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group">
                  <label>Answer Choices</label>
                  <textarea class="form-control form-readonly" rows="4" style="resize: none;" readonly>
  A. <%= q.answer_1 %>
  B. <%= q.answer_2 %>
  C. <%= q.answer_3 %>
  D. <%= q.answer_4 %>
                  </textarea>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="form-group">
                  <label>Answer:</label>
                  <select disabled class="form-control" id="answer">
                    <option value="1" <%= qqa.answer.to_i == 1 ? 'selected' : '' %>>Answer A</option>
                    <option value="2" <%= qqa.answer.to_i == 2 ? 'selected' : '' %>>Answer B</option>
                    <option value="3" <%= qqa.answer.to_i == 3 ? 'selected' : '' %>>Answer C</option>
                    <option value="4" <%= qqa.answer.to_i == 4 ? 'selected' : '' %>>Answer D</option>
                  </select>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="form-group">
                  <label>Marks to Award (Max <%= q.marks %>)</label>
                  <input readonly required="required" class="form-control form-readonly" type="number" name="marks[<%= qqa.id %>]" id="mark" value="<%= qqa.answer.to_i == q.correct_answer ? q.marks : '0' %>">
                </div>
              </div>
            </div>
          <hr class="pb-2 mt-1 mt-md-2 mb-3 mb-md-4">
        <% end %>
      <% end %>
      </div>
    </div>
    <div class="section-header d-md-flex align-items-center">
      <div class="section-header-right ml-auto mt-3 mt-md-4">
        <button type="submit" class="btn btn-primary text-uppercase">Submit</button>
      </div>
    </div>
  <% end %>
</div>