config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root to: 'users/homepage#index'

  devise_for :users, path: "user", controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
  }

  namespace :users, path: 'user' do
    get '/homepage', to: 'homepage#index', as: 'homepage'
    get '/do', to: 'quizzes#do_quiz', as: 'do_quiz'
    post '/do', to: 'quizzes#do_quiz_submit', as: 'do_quiz_submit'
    get '/history', to: 'quizzes#history', as: 'history'

    get '/profile', to: 'homepage#profile', as: 'profile'
    patch '/profile/update', to: 'homepage#update', as: 'update_profile'
    patch '/profile/password', to: 'homepage#change_password', as: 'change_password'

    resources :quizzes do
      post '/start', to: 'quizzes#start', as: 'start'

      get '/do/classic', to: 'quizzes#classic', as: 'classic'
      post '/do/classic', to: 'quizzes#submit_classic', as: 'submit_classic'
      get '/do/live', to: 'quizzes#live', as: 'live'
      post '/do/live', to: 'quizzes#submit_live', as: 'submit_live'

      get '/answers', to: 'quizzes#answers', as: 'answers'
      get '/answers/:id/mark', to: 'quizzes#mark', as: 'mark'
      post '/answers/:id/mark', to: 'quizzes#submit_mark', as: 'submit_mark'
    end
  end
end

app/views/layouts/shared/_users_nav.html.erb
  <!-- Page Sidebar -->
<div class="page-sidebar navbar-dark">
    <h4 class="nav-web-name mt-3 mt-md-5">IEGEP</h4>

    <!-- Sidebar Navigation -->
    <button class="navbar-toggler" data-toggle="collapse" data-target="#sidebar-nav" aria-controls="sidebar-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <nav class="side-navbar navbar navbar-expand-md">
        <div class="collapse navbar-collapse" id="sidebar-nav">
            <ul class="sidebar-nav nav nav-pills nav-fill">
                
                <li class="nav-item">
                    <a href="<%= root_path %>" class="nav-link d-flex <%= locals[:path] == 'homepage' ? 'active' : request.path == '/' ? 'active' : '' %>">                  
                        <span class="ml-2 mt-1" style="font-size: 16px">Homepage</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="<%= users_quizzes_path %>" class="nav-link d-flex  <%= locals[:path] == 'quizzes' ? 'active' : ''%>">
                        <span class="ml-2 mt-1" style="font-size: 16px">My Quizzes</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="<%= users_do_quiz_path %>" class="nav-link d-flex <%= locals[:path] == 'do' ? 'active' : ''%>">
                        <span class="ml-2 mt-1" style="font-size: 16px">Do A Quiz</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="<%= users_history_path %>" class="nav-link d-flex  <%= locals[:path] == 'history' ? 'active' : ''%>">
                        <span class="ml-2 mt-1" style="font-size: 16px">Quiz History</span>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- / Sidebar Navigation -->
</div>
<!-- / Page Sidebar -->

app/views/layouts/shared/_users_top.html.erb
 <!-- Top Navigation Bar -->
<nav class="top-navbar navbar navbar-expand navbar-light d-block d-md-flex">

    <!-- Top Navigation -->
    <ul class="top-nav navbar-nav ml-auto">
        <li class="user-nav-item nav-item dropdown active flex-fill">
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <%= link_to 'Edit Profile', users_profile_path, class: 'dropdown-item'%>
                <div class="dropdown-divider"></div>
                <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'dropdown-item'%>
            </div>
        </li>
        <li class="nav-item flex-fill">
            <a class="nav-link" href="<%= users_profile_path %>">
                <%= image_tag('gear-grey.svg') %>
            </a>
        </li>
        <li class="nav-item flex-fill">
            <%= link_to destroy_user_session_path, class:"nav-link", :data => {:confirm => 'Are you sure you want to logout?'}, method: :delete do%>
                <%= image_tag('logout-grey.svg') %>
            <% end %>
        </li>
    </ul>
    <!-- / Top Navigation -->
</nav>
<!-- / Top Navigation Bar -->