config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root to: 'users/homepage#index'

  devise_for :users, path: "user", controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
  }

  namespace :users, path: 'user' do
    get '/homepage', to: 'homepage#index', as: 'homepage'
    get '/do', to: 'quizzes#do_quiz', as: 'do_quiz'
    post '/do', to: 'quizzes#do_quiz_submit', as: 'do_quiz_submit'
    get '/history', to: 'quizzes#history', as: 'history'

    get '/profile', to: 'homepage#profile', as: 'profile'
    patch '/profile/update', to: 'homepage#update', as: 'update_profile'
    patch '/profile/password', to: 'homepage#change_password', as: 'change_password'

    resources :quizzes do
      post '/start', to: 'quizzes#start', as: 'start'

      get '/do/classic', to: 'quizzes#classic', as: 'classic'
      post '/do/classic', to: 'quizzes#submit_classic', as: 'submit_classic'
      get '/do/live', to: 'quizzes#live', as: 'live'
      post '/do/live', to: 'quizzes#submit_live', as: 'submit_live'

      get '/answers', to: 'quizzes#answers', as: 'answers'
      get '/answers/:id/mark', to: 'quizzes#mark', as: 'mark'
      post '/answers/:id/mark', to: 'quizzes#submit_mark', as: 'submit_mark'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :quizzes
  has_many :quiz_answers
end

app/controllers/users/base_controller.rb
class Users::BaseController < ActionController::Base
  breadcrumb 'Home', :root_path
  before_action :authenticate_user!
  before_action :get_user
  before_action :get_uri

  layout 'dashboard'

  private

  def get_user
    @user = current_user
  end

  def get_uri
    @base_url = URI(request.fullpath).path.split('/').last
  end
end

app/controllers/users/homepage_controller.rb
class Users::HomepageController < Users::BaseController
  def index

  end

  def profile

  end

  def update
    @update = @user.update!(profile_params)
    redirect_to root_path if @update
  end

  def change_password
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    
    @update = @user.update!(password_params)
    redirect_to request.referrer if @update
  end

  private

  def profile_params
    params.require(:user).permit(:name, :email)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/users/quizzes_controller.rb
class Users::QuizzesController < Users::BaseController
  

  def index
    @quizzes = @user.quizzes.order(start_date: :desc, end_date: :asc)
  end

  def new
    @quiz = Quiz.new
  end

  def create
    quiz = Quiz.create(quiz_params.merge(user: @user, code: rand(10000000...99999999)))

    count = params['questions']['number'].to_i - 1
    
    for i in 0..count do
      data = params['questions']['data'][i.to_s].split(',')
      if data[2] != 'deleted'
        Question.create(quiz: quiz, q_text: data[0], q_type: data[2], marks: data[1], answer_1: data[3], answer_2: data[4], answer_3: data[5], answer_4: data[6], correct_answer: data[7])
      end
    end
    
    redirect_to users_quizzes_path
  end

  def edit
    @quiz = Quiz.find(params[:id])
    @questions = @quiz.questions
    
    @q_array = []
    @questions.each do |q|
      @q_array << [q.q_text, q.marks, q.q_type, q.answer_1, q.answer_2, q.answer_3, q.answer_4, q.correct_answer]
    end
  end

  def update
    quiz = Quiz.find(params[:id])
    quiz.update(quiz_params)

    quiz.questions.destroy_all
    
    count = params['questions']['number'].to_i - 1
    
    for i in 0..count do
      data = params['questions']['data'][i.to_s].split(',')
      if data[2] != 'deleted'
        Question.create(quiz: quiz, q_text: data[0], q_type: data[2], marks: data[1], answer_1: data[3], answer_2: data[4], answer_3: data[5], answer_4: data[6], correct_answer: data[7])
      end
    end
    
    redirect_to users_quizzes_path
  end

  def destroy
    quiz = Quiz.find(params[:id])
    
    quiz.questions.each do |q|
      q.question_answers.destroy_all
    end
    quiz.questions.destroy_all

    quiz.update(user: nil)
    quiz.destroy
  end

  def do_quiz
    
  end

  def do_quiz_submit
    quiz = Quiz.find_by(code: params[:code].to_i)

    if !quiz.nil?
      if DateTime.now >= DateTime.new(quiz.start_date.year, quiz.start_date.month, quiz.start_date.day, quiz.start_time.hour, quiz.start_time.min, quiz.start_time.sec, quiz.start_time.zone)
        if DateTime.now <= DateTime.new(quiz.end_date.year, quiz.end_date.month, quiz.end_date.day, quiz.end_time.hour, quiz.end_time.min, quiz.end_time.sec, quiz.end_time.zone)
          if quiz.q_type == 'classic'
            render :json => {id: quiz.id, type: 'classic'}
          else
            render :json => {id: quiz.id, type: 'live'}
          end
        else
          render :json => {id: 0, type: 'fail'}
        end
      else
        render :json => {id: 0, type: 'fail'}
      end
    else
      render :json => {id: 0, type: 'fail'}
    end
  end

  def history
    @history = @user.quiz_answers
  end

  def start

  end

  def classic
    @quiz = Quiz.find(params[:quiz_id])
    @answer = QuizAnswer.new

    @end_time = DateTime.new(@quiz.end_date.year, @quiz.end_date.month, @quiz.end_date.day, @quiz.start_time.hour, @quiz.start_time.min, @quiz.start_time.sec, @quiz.start_time.zone).strftime("%b %-d, %Y %H:%M:%S")
  end

  def submit_classic
    quiz = Quiz.find(params[:quiz_id])
    qa = QuizAnswer.create(quiz: quiz, user: @user, start_date: quiz.start_date, end_date: quiz.end_date, start_time: quiz.start_time, end_time: quiz.end_time)
    
    params['answers'].each do |a|
      QuestionAnswer.create(question_id: a[0], quiz_answer: qa, marks: nil, answer: a[1])
    end
    
    redirect_to root_path
  end

  def live
    @quiz = Quiz.find(params[:quiz_id])
    @host = false
    
    if @quiz.user != @user
      @qa = QuizAnswer.where(user: @user).where(quiz: @quiz).first
      if @qa.nil?
        @qa = QuizAnswer.create(quiz: @quiz, user: @user, start_date: @quiz.start_date, end_date: @quiz.end_date, start_time: @quiz.start_time, end_time: @quiz.end_time)
      end
    else
      @host = true;
    end
  end

  def submit_live
  end

  def answers
    @quiz = Quiz.find(params[:quiz_id])
  end

  def mark
    @quiz = Quiz.find(params[:quiz_id])
    @qa = QuizAnswer.find(params[:id])
  end

  def submit_mark
    total = 0
    params['marks'].each do |m|
      QuestionAnswer.find(m[0].to_i).update(marks: m[1].to_i)
      total += m[1].to_i
    end

    QuizAnswer.find(params[:id]).update(total_marks: total)
    
    redirect_to users_quiz_answers_path(params[:quiz_id])
  end

  private

  def quiz_params
    params.require(:quiz).permit(:name, :q_type, :description, :start_date, :end_date, :start_time, :end_time)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
    flash[:warning] = 'You has been signed out.'
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/views/users/homepage/index.html.erb
<meta name="turbolinks-visit-control" content="reload">
<!-- Page Content -->
<div class="page-content">
  <h1 class="mb-2">Welcome <%= @user.name %> to IEGEP!</h1>
  <hr class="pb-2 my-4">

  <!-- TODO : Replace style with class -->
  <div class="card-deck flex-column flex-lg-row">
      <div class="info-box card mb-30">
          <div class="card-body">
              <div class="info-group text-left">
                  <label style="font-size: 1.5em; color:black">Quizzes Created</label>
              </div>
              <div style="height:180px">
                  <h1 style="font-size: 8rem"><%= @user.quizzes.count %></h1>
              </div>
              <div class="btn-group info-box-action d-flex" role="group">
                  <a href="<%= users_quizzes_path %>" class="info-box-btn-main flex-fill btn btn-blue-gradient" style="font-size: 1.3em; text-align: center; padding: 1rem !important;">Create New Quiz</a>
              </div>
          </div>
      </div>
      <div class="info-box card mb-30">
          <div class="card-body">
              <div class="info-group text-left">
                  <label style="font-size: 1.5em; color:black">Quizzes Done</label>
              </div>
              <div style="height:180px">
                  <h1 style="font-size: 8rem"><%= @user.quiz_answers.count %></h1>
              </div>

              <div class="btn-group info-box-action d-flex" role="group">
                  <a href="<%= users_do_quiz_path %>" class="info-box-btn-main flex-fill btn btn-blue-gradient" style="font-size: 1.3em; text-align: center; padding: 1rem !important;">Do A Quiz</a>
              </div>
          </div>
      </div>
  </div>
</div>

app/views/users/homepage/profile.html.erb
<!-- Page Content -->
<div class="page-content">
    <!-- Page Header -->
     <div class="page-header d-flex flex-column flex-md-row align-items-md-center">
      <div class="page-header-left flex-fill">
          <div class="page-header-title d-flex">
              <img src="https://img.icons8.com/nolan/60/gear.png"/>
              <div class="page-info mt-3">
                  <h5 class="page-title">Update Profile</h5>
              </div>
          </div>
      </div>
  </div>

    <!-- / Page Header -->

    <!-- Form - Update Profile -->
    <%= form_for(:user, url: users_update_profile_path, id: 'profile-edit', method: :patch, :html => {:multipart => true}) do |f|%>
        <!-- Section Header - Update Profile -->
        <div class="section-header d-md-flex align-items-center">
            <div class="section-header-left flex-fill">
                <a href="<%= root_path %>" class="page-btn-link">
                    <i class="icon icon-reply"></i>
                    Back to Homepage
                </a>
            </div>
            
        </div>
        <!-- / Section Header - Update Profile -->

        <!-- Section - Update Profile -->
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Update Profile</h5>
            </div>
            <div class="card-body">
                <!-- Form Fields -->
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" id="name" name="user[name]" class="form-control" name="name" value="<%= @user.name%>" required>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="email">Email Address</label>
                            <input type="email" id="email"  name="user[email_address]" class="form-control" name="email" value="<%= @user.email%>" required>
                        </div>
                    </div>
                </div>
                <!-- / Form Fields -->
            </div>
        </div>
        <div class="row pt-4">
            <div class="col-lg-12 text-right">
                <div class="section-header-right ml-auto">
                    <button type="submit" class="btn btn-primary text-uppercase">Update</button>
                </div>
            </div>
        </div>
        <!-- / Section - Update Profile -->
   <% end %>
    <!-- / Form - Update Profile -->

    <!-- Form - Change Your Password -->
    <%= form_for(:user, url: users_change_password_path, id: 'password-change', method: :patch) do |f|%>
        <!-- Section Header - Change Your Password -->
        <div class="section-header d-md-flex align-items-center">
            <div class="section-header-right ml-auto">
            </div>
        </div>
        <!-- / Section Header - Change Your Password -->

        <!-- Section - Change Your Password -->
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Change Your Password</h5>
            </div>
            <div class="card-body">
                <!-- Form Fields -->
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" class="form-control" name="user[password]" required>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="password-confirmation">Retype Password</label>
                            <input type="password" class="form-control" name="user[password_confirmation]" required>
                        </div>
                    </div>
                </div>
                <!-- / Form Fields -->
            </div>
            <div class="card-footer pt-4">
             <div class="row">
                <div class="col-12 text-right">
                    <div class="section-header-right ml-auto">
                        <button type="submit" class="btn btn-primary text-uppercase">Save</button>
                    </div>
                </div>
            </div>
            </div>
        </div>
        <!-- / Section - Change Your Password -->
    <% end %>
    <!-- / Form - Change Your Password -->
</div>
<!-- / Page Content -->
